### ISSUE TITLE
Status 404 with returned public url

### ISSUE THREAD

**Issue by bsnbu** [supabase-community/supabase-dart#101]
Hi all,

I'm trying to follow the official flutter guide and noticed that after updating the avatar the console logged the following error,
`HTTP request failed, statusCode: 400, https://audittedsubdomain.supabase.co/storage/v1/object/public/avatars/add19f9a-5eae-4d05-9529-cdbb3acfa270.jpg`
I noticed that the public url I got from the dashboard starts with `https://audittedsubdomain.supabase.in` instead of `supbase.co`, could this be the cause here?

Thank you!

Best regards.

**Comment by dshukertjr** [comment]
Hi @bsnbu ! Thank you so much for opening an issue for this. 

Do you have an example of working public URL? I changed the URL you provided to `supabase.in` like [this](https://audittedsubdomain.supabase.in/storage/v1/object/public/avatars/add19f9a-5eae-4d05-9529-cdbb3acfa270.jpg), but couldn't load image. 

Also, could you confirm that the bucket you are using is set to public?
<img width="524" alt="Screen Shot 2022-03-23 at 19 02 20" src="https://user-images.githubusercontent.com/18113850/159673851-ff6e63c4-31cd-420e-9b98-3e5ff71ca662.png">

**Comment by bdlukaa** [comment]
Closing as inactive.
