### ISSUE TITLE
Functions-dart repo is not public yet

### ISSUE THREAD

**Issue by Vinzent03** [supabase-community/supabase-dart#106]
I see that supabase-dart supports the new Supabase edge functions and the needed `functions_client` package is released on [pub.dev](https://pub.dev/packages/functions_client), but the corresponding GitHub [repository](https://github.com/supabase-community/functions-dart) is not public currently.

**Comment by dshukertjr** [comment]
@Vinzent03 Great call! Thanks for noticing and letting us know! I have made it public right now!
