### ISSUE TITLE
Dart library rework

### ISSUE THREAD

**Issue by bdlukaa** [supabase-community/supabase-dart#109]
We currently have 7 dart libraries: 
- [supabase-flutter](https://github.com/supabase-community/supabase-flutter);
- [supabase-dart](https://github.com/supabase-community/supabase-dart);
- [postgrest-dart](https://github.com/supabase-community/postgrest-dart);	
- [gotrue-dart](https://github.com/supabase-community/gotrue-dart);
- [realtime-dart](https://github.com/supabase-community/realtime-dart);
- [storage-dart](https://github.com/supabase-community/storage-dart);
- [functions-dart](https://github.com/supabase-community/functions-dart);

Most of them needs a rework:

- Use most recent dart code patterns and linting:
- Error handling using `try/catch`
- Helpful inline documentation
- Bugfixes that do not depend on the backend to change
  - [x] gotrue (https://github.com/supabase-community/gotrue-dart/pull/74)
  - [x] realtime (https://github.com/supabase-community/realtime-dart/pull/44)
  - [x] postgrest (https://github.com/supabase-community/postgrest-dart/pull/69)
  - [x] storage (https://github.com/supabase-community/storage-dart/pull/30)
  - [x] functions
- [x] Unify all the issues in a single repository (`supabase-flutter`). (Related to #96)

**Comment by DanMossa** [comment]
Amazing! Are this and supabase-flutter going to be the only repos that are unified ?
