### ISSUE TITLE
getx +supabase

### ISSUE THREAD

**Issue by CodeKinggggggg** [supabase-community/supabase-dart#126]
It is difficult to load data from DB using getx. What should I do?

**Comment by bdlukaa** [comment]
Can you provide more info about your issue?

**Comment by CodeKinggggggg** [comment]
I'm trying to use the MVC pattern. 

Specifically, 
In controller, 

class PostsController extends GetxController {
  SupabaseManager supabaseManager = SupabaseManager();
  var postList = <PostList>[].obs;

  @override
  void onInit() {
    super.onInit();
    readData();
  }

  Future<void> readData() async {
    var postData = await supabaseManager.readData();
    if (postData != null) {
      postList.value = postData;
    }
  }


In Model, 

class PostList {
  final int id;
  final String title;
  final String userName;
  final String gameMode;
  final int? favorite;
  final int? chat;
  final String date;

  PostList(
      {required this.id,
      required this.title,
      required this.userName,
      required this.gameMode,
      required this.favorite,
      required this.chat,
      required this.date});
}


In View,

lass HomePostList extends StatelessWidget {
  final postsController = Get.put(PostsController());

  @override
  Widget build(BuildContext context) {
    return Obx(
      () {
        return ListView.separated(
          padding: EdgeInsets.only(top: 10),
          separatorBuilder: (BuildContext context, int index) {
            return Divider(
              thickness: 1,
            );
          },
          itemCount: postsController.postList.length,
          itemBuilder: (BuildContext context, int index) {
            print(postsController.postList.length);
            return ListTile(
              onTap: () => {Get.toNamed('/postDetail')},
              leading: CircleAvatar(
                child: Icon(Icons.person_outline_rounded),
              ),
              title: Text(postsController.postList[index].title, maxLines: 1),
              subtitle: Column(
                children: [
                  Row(
                    children: [
                      Text(postsController.postList[index].userName),
                      SizedBox(
                        width: double.minPositive,
                      ),
                    ],
                  ),
                  Row(
                    children: [
                      Text(postsController.postList[index].gameMode),
                      SizedBox(width: 10),
                      Expanded(
                          child: Text(postsController.postList[index].date)),
                      Row(
                        children: [
                          Icon(Icons.chat_bubble_outline, size: 15),
                          Text('${postsController.postList[index].chat}'),
                          Icon(Icons.favorite_border_outlined, size: 15),
                          Text('${postsController.postList[index].favorite}'),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }
}



Sorry for being so new.

**Comment by CodeKinggggggg** [comment]
> 문제에 대한 자세한 정보를 제공할 수 있습니까?

.

**Comment by bdlukaa** [comment]
Can you provide more information about your issue?
