### ISSUE TITLE
Boolean values comes with null in realtime events

### ISSUE THREAD

**Issue by gcostaapps** [supabase-community/supabase-dart#73]
Hi, I have a table that has some boolean values and I'm listening to it through .on().subscribe(). Whenever I update a value the payload that I receive comes with boolean values as null. Even when I update a boolean value, the update event is triggered but the value of the property comes with null.

**Comment by bdlukaa** [comment]
I believe this was fixed on https://github.com/supabase-community/realtime-dart/pull/30

**Comment by bdlukaa** [comment]
Duplicate of https://github.com/supabase-community/realtime-dart/issues/29, which was fixed by https://github.com/supabase-community/realtime-dart/pull/30

Closing as solved!
