### ISSUE TITLE
Kong Error : No Api key found in request

### ISSUE THREAD

**Issue by dukesx** [supabase-community/supabase-dart#76]
# Bug report

## Describe the bug

I am trying to use flutter client of supabase to send a password reset link, however i am using "redirect to" param to redirect the user to my app, where i show my user the reset form. When the user clicks on reset link received in email, the user receives the error 

Which Link Do i receive ? 
```
https://[hidden-project-id].supabase.co/auth/v1/verify?token=zBhzNsGKt2ICKpaD6-zlrw&type=recovery&redirect_to=com.mobile.app://reset-callback/
```

Where does the above link redirect to (when clicked) ?

```
https://[hidden-project-id].supabase.co/auth/v1/com.mobile.app://reset-callback/#error_code=404&error_description=User+not+found
```

Client reports no error and so far the user exists in the Dashboard > Auth > Users with the email.

**Note: I have already added the "redirect url" in my additional redirect urls, seperated by comma (since there are two) and i have also added the deep links**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use Supabase Flutter
2. have a user registered using email
3. reset password using .**resetPasswordForEmail**() function with redirect url as "com.app_name.etc://reset-callback"
4. Receive the email
4. Click the email link
5. See Kong Error

## Expected behavior

Link should redirect user to my app's deep link (as entered in redirect url param) 

## Screenshots

![Untitled](https://user-images.githubusercontent.com/5988991/147595606-6035d94c-c088-42ae-8ce0-42a415d2a46e.png)

Url that causes this: 
```
https://[hidden-project-id].supabase.co/auth/v1/com.mobile.app://reset-callback/#error_code=404&error_description=User+not+found
```

## System information

- OS: Android 11
- Browser (Noop)
- Version of supabase_flutter (^0.2.9)

**Comment by phamhieu** [comment]
@kangmingtay is it gotrue server bug with custom redirect URL scheme for mobile ?

**Comment by dukesx** [comment]
Anyone help ? My app launch is in few days and this issue is now a bummer for my patients.

**Comment by kangmingtay** [comment]
hey @dukesx, can you please email support@supabase.io so we can investigate your project if its urgent? thanks!

**Comment by dukesx** [comment]
@kangmingtay i have emailed supabase support.

**Comment by Jay-flow** [comment]
I have a similar issue.
Is there anything that progress?

**Comment by phamhieu** [comment]
Hi @Jay-flow can you open a new issue with related detail for your problem.

**Comment by Jay-flow** [comment]
In my case, there is a problem with the signup

It receives normally when signing up by e-mail, but when I click the link I received, an error occurs as shown in the picture below.
![Screenshot_2022-01-14-14-59-15-994_com android browser](https://user-images.githubusercontent.com/29420674/149460640-95771f09-6cdf-4e05-80a6-9eb0c30f1cd3.jpg)


The redirect URL is as follows.
https://${API_URL}/auth/v1/${DEEP_LINK}/#access_token=${ACCESS_TOKEN}&expires_in=3600&refresh_token=${REFRESH_TOKEN}token_type=bearer&type=signup

I confirmed that the deep link is configured on Android.
