### ISSUE TITLE
Kong Error : No Api key found in request

### ISSUE THREAD

**Issue by Jay-flow** [supabase-community/supabase-dart#86]
# Kong Error : No Api key found in request

related #76 

In my case, there is a problem with the signup

It receives normally when signing up by e-mail, but when I click the link I received, an error occurs as shown in the picture below.
![Screenshot_2022-01-14-14-59-15-994_com android browser](https://user-images.githubusercontent.com/29420674/149460640-95771f09-6cdf-4e05-80a6-9eb0c30f1cd3.jpg)

The redirect URL is as follows.
https://${API_URL}/auth/v1/${DEEP_LINK}/#access_token=${ACCESS_TOKEN}&expires_in=3600&refresh_token=${REFRESH_TOKEN}token_type=bearer&type=signup

I confirmed that the deep link is configured on Android.

I can check the user after clicking the link.

![Screenshot_20220114_151642](https://user-images.githubusercontent.com/29420674/149460922-27b803fa-a132-477f-b294-5c36201fe193.png)

**Comment by phamhieu** [comment]
@Jay-flow have you tested your deeplink config?

- You can go to this website https://halgatewood.com/deeplink from your test device
- input the deeplink and click load button
  - if your mobile app launch successfully then the deeplink config works properly

**Comment by Jay-flow** [comment]
@phamhieu 

I'm sorry. It was my mistake.
I didn't know deep link shouldn't include '_'
When I change the underbar to a dash, it moves to the app normally.

I have one more question. When I go to the app, I still go to the sign-in page, so I don't know what to do after that. Can you give me any advice on this?

Thank you for your help
